In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/santa-2025/sample_submission.csv
/kaggle/input/santa-dataset/submission (1).csv
/kaggle/input/santa-dataset/submission (4).csv
/kaggle/input/santa-dataset/submission (3).csv
/kaggle/input/santa-dataset/submission (5).csv
/kaggle/input/santa-dataset/submission.csv

In [2]:
df1=pd.read_csv("/kaggle/input/santa-dataset/submission (1).csv")
df2=pd.read_csv("/kaggle/input/santa-dataset/submission (3).csv")
df3=pd.read_csv("/kaggle/input/santa-dataset/submission (4).csv")
df4=pd.read_csv("/kaggle/input/santa-dataset/submission (5).csv")
df5=pd.read_csv("/kaggle/input/santa-dataset/submission.csv")

In [3]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20100 entries, 0 to 20099
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      20100 non-null  object
 1   x       20100 non-null  object
 2   y       20100 non-null  object
 3   deg     20100 non-null  object
dtypes: object(4)
memory usage: 628.3+ KB

In [4]:
df1.head(5)

,id,x,y,deg
0,001_0,s-38.50678828401222375533,s19.89318421958255456161,s45.00000000000000000000
1,002_0,s-3.50266882337951779292,s1.90138090839184759062,s203.62937773055205070705
2,002_1,s-3.81086296262207779861,s1.37846239378111645735,s23.62937773055205070705
3,003_0,s0.67658315671039304107,s1.22043378943991798202,s155.13405193710082130565
4,003_1,s1.26892421232347896165,s1.31597472349029676053,s66.37062226934300213088

In [5]:
df2.head(5)

,id,x,y,deg
0,001_0,s-47.93014665278157337980,s58.50504507378155949482,s45.00000000000000000000
1,002_0,s-4.77111626803881527792,s0.92855990161327794929,s23.62937773055205070705
2,002_1,s-4.46292212879625527222,s1.45147841622400908257,s203.62937773055205070705
3,003_0,s0.67658315671039304107,s1.22043378943991798202,s155.13405193710082130565
4,003_1,s1.26892421232347896165,s1.31597472349029676053,s66.37062226934300213088